#!/bin/bash
echo "Installing virtualenv package..."
sudo pip3 install virtualenv
echo "Initializing virtualenv..."
virtualenv venv
echo "Installing python modules to venv..."
venv/bin/pip install -r requirements.txt
echo "Installation complete. You may start the project now."
read -n 1 -s -r -p "Press any key to continue"
